using CommandLine;

namespace RPOrganizer;

internal partial class Program
{
    public class CommandLineOptions
    {
        [Option('v', "verbose", Required = false, HelpText = "Set output to verbose messages.")]
        public bool Verbose { get; set; }

        [Option('i', "input", Required = true, HelpText = "File generated by RP++")]
        public string InputFile { get; set; }

        [Option('o', "output", Required = true, HelpText = "Organized gadgets output file")]
        public string OutputFile { get; set; }
    }
}
